### ISSUE TITLE
PSR-4 Autoloading warning

### ISSUE THREAD

**Issue by PAXANDDOS** [francerz/php-sql-builder#1]
Getting these two warnings after generating autoload files. Not a big deal, but still they kinda hurt my eyes 😅 decided to let you know. Latest version.

`Class Francerz\SqlBuilder\Expressions\Comparison\RegexpExpression located in ./vendor/francerz/sql-builder/src/Expressions/Comparison/RegexpExpresion.php does not comply with psr-4 autoloading standard. Skipping. `
                                                                                                                                                                 
`Class Francerz\PowerData\TypedCollection located in ./vendor/francerz/php-power-data/src/Typed/TypedCollection.php does not comply with psr-4 autoloading standard. Skipping.`

Apart from that, thats a great tool!

**Comment by francerz** [comment]
Thank you for reporting.

Fixes are applied and will be released in next version.

Greetings!

**Comment by PAXANDDOS** [comment]
Thanks for the update! `RegexpExpression` is now fixed but the `TypedCollection` error still persists 👀 

![image](https://user-images.githubusercontent.com/40315177/201678960-8fa92ba7-1d67-4907-8a80-6ab6457c9f71.png)
